#!/bin/bash

#date is for file name and autosupport name.
DATE=`date '+%m-%d-%Y.%H:%M:%S'`

#Create a brandnew temp dir. 
TEMP=`mktemp -d`

# Read the hostname and use it in the header and autosupport name. 
HOSTNAME=''

#create the TEMP/autosupport-date folder. 
ASUPDIR="autosupport-$DATE"
echo $ASUPDIR 


#List of commands and files to gather.
COMMANDLIST=("df -h" "zpool status" "zfs list -t snapshot" "ifconfig" "vmadm list")
COPYLIST=("/usbkey/config")

