#!/bin/bash

# date is for file name and autosupport name.
DATE=`date '+%m-%d-%Y.%H:%M:%S'`

# Create a brandnew temp dir. 
TEMP=`mktemp -d`

# create the TEMP/autosupport-date folder. 
ASUPDIR="$HOSTNAME-$DATE-autosupport"
echo $ASUPDIR 


# List of commands and files to gather.
COMMANDLIST=("dpkg -l" "dmesg -T" "df" "df -h" "ls /etc/init.d") 
COPYLIST=("/etc/hostname" "/etc/network/interfaces" "/etc/resolv.conf" "/etc/apt/sources.list") 


echo $COMMANDLIST
